### ISSUE TITLE
HTML5?

### ISSUE THREAD

**Issue by Paul-Ollivier** [steverichey/openfl-gif#1]
Hi Steve, I'm trying to use your library for HTML5, but the sys.io.File doesn't work with this target. I've had a look at js.html.File but I'm not familiar with JS at all ( that's why I use OpenFL / haXe :> ).

Any tip on what I should do, or do you think it's even possible to tweak your code and target HMTL5?

**Comment by steverichey** [comment]
Judging by [this](https://stackoverflow.com/questions/35038884/download-file-from-bytes-in-javascript) and [this](https://stackoverflow.com/questions/27946228/file-download-a-byte-array-as-a-file-in-javascript-extjs), it looks like you should be able to wrap the encoder bytes in a `Uint8Array`, and then wrap that in a `Blob`, and then you can download that as a file.

However, I rarely use Haxe to target JS, so if you need more help I'd suggest you ask on the [Haxe Google Group](https://groups.google.com/forum/?hl=en#!forum/haxelang) or the [OpenFL forums](http://community.openfl.org/).

**Comment by anissen** [comment]
There is also a [similar library](https://github.com/snowkit/gif) (platform agnostic) that you can use for encoding gifs. It supports JavaScript as well as sys targets.
